FLTKDIR=C:\fltk-1.1.9
CXX=CL
CXXFLAGS=/TP /nologo /MD /EHsc /I. /I.. /I$(FLTKDIR) /wd4996 \
	 /DVS2000 /DMICROSOFT /DWIN32 /D_WINDOWS /D_CRT_SECURE_NO_DEPRECATE \
	 /Zi
LINKFLAGS=/DEBUG
FLTKLIBS=/LIBPATH:$(FLTKDIR)\lib \
	      fltk.lib \
	      wsock32.lib  comctl32.lib kernel32.lib user32.lib  gdi32.lib \
	      winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib \
	      oleaut32.lib uuid.lib \
	      /nologo /machine:x86 /NODEFAULTLIB:libcmt /SUBSYSTEM:CONSOLE

BINS=test-app.exe

default: $(BINS)

clean: FORCE
	-del /q *.o
	-del /q *.obj
	-del /q *.exe
	-del /q *.manifest 
	-del /q *.ilk
	-del /q *.pdb

MyConstantDialog.obj: MyConstantDialog.C MyConstantDialog.H
	$(CXX) $(CXXFLAGS) MyConstantDialog.C -c

MyBoxInfoDialog.obj: MyBoxInfoDialog.C MyBoxInfoDialog.H
	$(CXX) $(CXXFLAGS) MyBoxInfoDialog.C -c

Subs.obj: Subs.C Subs.H
	$(CXX) $(CXXFLAGS) Subs.C -c

MyBox.obj: MyBox.C MyBox.H
	$(CXX) $(CXXFLAGS) MyBox.C -c

MyButton.obj: MyButton.C MyButton.H
	$(CXX) $(CXXFLAGS) MyButton.C -c

MyDesk.obj: MyDesk.C MyDesk.H
	$(CXX) $(CXXFLAGS) MyDesk.C -c

test-app.exe: ../Fl_OpDesk.obj ../Fl_OpButton.obj ../Fl_OpBox.obj \
		MyConstantDialog.obj MyBoxInfoDialog.obj \
		MyBox.obj MyButton.obj MyDesk.obj Subs.obj \
		MyDesk.H \
		test-app.C
 	$(CXX) $(CXXFLAGS) test-app.C \
 	    /link $(LINKFLAGS) ../Fl_OpDesk.obj ../Fl_OpButton.obj ../Fl_OpBox.obj \
	    	  MyConstantDialog.obj MyBoxInfoDialog.obj \
		  MyBox.obj MyButton.obj MyDesk.obj Subs.obj $(FLTKLIBS) /out:$@

foo.obj: foo.C
	$(CXX) $(CXXFLAGS) foo.C -c

foo.exe: foo.obj
 	$(CXX) $(CXXFLAGS) foo.C \
 	    /link $(LINKFLAGS) $(FLTKLIBS) /out:$@

# DO NOT REMOVE THE FOLLOWING LINES
FORCE:
